package org.eteamcs.dao;

import java.util.List;

import org.eteamcs.model.Companie;
import org.eteamcs.model.CompanySearch;

/**
 * DAO Interface to table companies
 * @author Paulo Neves 
 * Generated by Javalee v. 1.1
 * $Id$
 */
public interface ICompanieDAO extends IDAO {

	public List getCompanies(CompanySearch cs);
	
	public List getCompaniesByInitial(String letter);
	
	public Companie getCompanie(java.lang.Long companyId);
	
	public Companie getCompanieByName(String name);
	
	public void saveCompanie(Companie companie);
	
	public void removeCompanie(java.lang.Long companyId);
	
}
