
package org.eteamcs.dao;

import java.util.List;

import org.eteamcs.model.Contact;
import org.eteamcs.model.ContactSearch;

/**
 * DAO Interface to table contacts
 * @author Paulo Neves 
 * Generated by Javalee v. 1.1
 * $Id$
 */
public interface IContactDAO extends IDAO {

	public List getContacts(ContactSearch cs);
	
	public List getContactsByInitial(String initial);
	
	public List getContactsByCompanyId(Long companyId);
	
	public Contact getContact(java.lang.Long contactId);
	
	public void saveContact(Contact contact);
	
	public void removeContact(java.lang.Long contactId);
	
}
