package org.eteamcs.model;

import java.util.Date;

/**
 * Entity Bean for the table Category
 * @author Paulo Neves
 * Generated by Javalee v. 1.1
 * $Id$
 */
public class Category extends BaseObject{
    private java.lang.Long categoryId;
    private java.lang.String name;
    private java.lang.Long parentId;
    private java.lang.String username;
    private java.util.Date creationDate;
    private String checked;
    private Integer column;

    /**
     * Constructor
     */
    public Category() {
    	
    }
	
    /**
     * Constructor
     */
    public Category( Long categoryId, String name, Long parentId, 
    		         String username, Date creationDate ) {
    	this.categoryId = categoryId;
    	this.name = name;
    	this.parentId = parentId;
    	this.username = username;
    	this.creationDate = creationDate;
	}	

    public Category(Category cat) {
    	this.categoryId = cat.categoryId;
    	this.name = cat.name;
    	this.parentId = cat.parentId;
    	this.username = cat.username;
    	this.creationDate = cat.creationDate;
    	
    }
    
    
	/**
	 * @return Returns the categoryId.
	 */
	public java.lang.Long getCategoryId() {
		return categoryId;
	}
	/**
	 * @param categoryId The categoryId to set.
	 */
	public void setCategoryId(java.lang.Long categoryId) {
		this.categoryId = categoryId;
	}
	/**
	 * @return Returns the creationDate.
	 */
	public java.util.Date getCreationDate() {
		return creationDate;
	}
	/**
	 * @param creationDate The creationDate to set.
	 */
	public void setCreationDate(java.util.Date creationDate) {
		this.creationDate = creationDate;
	}
	/**
	 * @return Returns the name.
	 */
	public java.lang.String getName() {
		return name;
	}
	/**
	 * @param name The name to set.
	 */
	public void setName(java.lang.String name) {
		this.name = name;
	}
	/**
	 * @return Returns the parentId.
	 */
	public java.lang.Long getParentId() {
		return parentId;
	}
	/**
	 * @param parentId The parentId to set.
	 */
	public void setParentId(java.lang.Long parentId) {
		this.parentId = parentId;
	}
	/**
	 * @return Returns the username.
	 */
	public java.lang.String getUsername() {
		return username;
	}
	/**
	 * @param username The username to set.
	 */
	public void setUsername(java.lang.String username) {
		this.username = username;
	}
	
	/**
	 * @return Returns the checked.
	 */
	public String getChecked() {
		return checked;
	}
	/**
	 * @param checked The checked to set.
	 */
	public void setChecked(String checked) {
		this.checked = checked;
	}

	public Integer getColumn() {
		return column;
	}

	public void setColumn(Integer column) {
		this.column = column;
	}
	
	
}

