
package org.eteamcs.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Entity Bean for the table companies
 * @author Paulo Neves
 * Generated by Javalee v. 1.1
 * $Id$
 */
public class Companie extends BaseObject {

    
    private java.lang.Long companyId;
    private java.lang.String name;
    private java.lang.String phone;
    private java.lang.String fax;
    private java.lang.String email;
    private java.lang.String url;
    private java.lang.String streetAddress;
    private java.lang.String postalCode;
    private String bairro;
    private java.lang.String city;
    private String state;
    private java.lang.String country;
    private java.lang.String postStreetAddress;
    private java.lang.String postPostalCode;
    private java.lang.String postCity;
    private java.lang.String postState;
    private java.lang.String postCountry;
    private List relations;
    private java.lang.Integer category;    
    private String comments;
    private Date lastUpdate;
    private java.lang.String username;
    private java.util.Date creationDate;

    /**
     * Constructor
     */
    public Companie() {
    	name = "";
    	phone = "";
    	fax = "";
    	email= "";
    	url = "";
    	streetAddress = "";
    	postalCode = "";
    	city = "";
    	country = "";
    	postStreetAddress = "";
    	postPostalCode = "";
    	postCity = "";
    	postState = "";
    	postCountry = "";
    	username = "";
    	creationDate = new Date();
    	this.relations = new ArrayList();
    }
	
    /**
     * Constructor
     */
    public Companie(java.lang.Long companyId, 
						java.lang.String name, 
						java.lang.String phone, 
						java.lang.String fax, 
						java.lang.String email, 
						java.lang.String url, 
						java.lang.String streetAddress, 
						java.lang.String postalCode, 
						java.lang.String city, 
						java.lang.String country, 
						java.lang.String postStreetAddress, 
						java.lang.String postPostalCode, 
						java.lang.String postCity, 
						java.lang.String postState, 
						java.lang.String postCountry, 
						java.lang.String username, 
						java.util.Date creationDate
						) {
		this.companyId=companyId;
		this.name=name;
		this.phone=phone;
		this.fax=fax;
		this.email=email;
		this.url=url;
		this.streetAddress=streetAddress;
		this.postalCode=postalCode;
		this.city=city;
		this.country=country;
		this.postStreetAddress=postStreetAddress;
		this.postPostalCode=postPostalCode;
		this.postCity=postCity;
		this.postState=postState;
		this.postCountry=postCountry;
		this.username=username;
		this.creationDate=creationDate;
		
		
	}	

    
    public java.lang.Long getId() {
      return this.companyId;
    }    
         
    public void setCompanyId(java.lang.Long companyId) {
      this.companyId = companyId;
    }


    public java.lang.Long getCompanyId() {
      return this.companyId;
    }    
    
    public void setName(java.lang.String name) {
      this.name = name;
    }

    public java.lang.String getName() {
      return this.name;
    }
    
    public void setPhone(java.lang.String phone) {
      this.phone = phone;
    }

    public java.lang.String getPhone() {
      return this.phone;
    }
    
    public void setFax(java.lang.String fax) {
      this.fax = fax;
    }

    public java.lang.String getFax() {
      return this.fax;
    }
    
    public void setEmail(java.lang.String email) {
      this.email = email;
    }

    public java.lang.String getEmail() {
      return this.email;
    }
    
    public void setUrl(java.lang.String url) {
      this.url = url;
    }

    public java.lang.String getUrl() {
      return this.url;
    }
    
    public void setStreetAddress(java.lang.String streetAddress) {
      this.streetAddress = streetAddress;
    }

    public java.lang.String getStreetAddress() {
      return this.streetAddress;
    }
    
    public void setPostalCode(java.lang.String postalCode) {
      this.postalCode = postalCode;
    }

    public java.lang.String getPostalCode() {
      return this.postalCode;
    }
    
    public void setCity(java.lang.String city) {
      this.city = city;
    }

    public java.lang.String getCity() {
      return this.city;
    }
    
    public void setCountry(java.lang.String country) {
      this.country = country;
    }

    public java.lang.String getCountry() {
      return this.country;
    }
    
    public void setPostStreetAddress(java.lang.String postStreetAddress) {
      this.postStreetAddress = postStreetAddress;
    }

    public java.lang.String getPostStreetAddress() {
      return this.postStreetAddress;
    }
    
    public void setPostPostalCode(java.lang.String postPostalCode) {
      this.postPostalCode = postPostalCode;
    }

    public java.lang.String getPostPostalCode() {
      return this.postPostalCode;
    }
    
    public void setPostCity(java.lang.String postCity) {
      this.postCity = postCity;
    }

    public java.lang.String getPostCity() {
      return this.postCity;
    }
    
    public void setPostState(java.lang.String postState) {
      this.postState = postState;
    }

    public java.lang.String getPostState() {
      return this.postState;
    }
    
    public void setPostCountry(java.lang.String postCountry) {
      this.postCountry = postCountry;
    }

    public java.lang.String getPostCountry() {
      return this.postCountry;
    }
    
    public void setUsername(java.lang.String username) {
      this.username = username;
    }

    public java.lang.String getUsername() {
      return this.username;
    }
    
    public void setCreationDate(java.util.Date creationDate) {
      this.creationDate = creationDate;
    }

    public java.util.Date getCreationDate() {
      return this.creationDate;
    }
    
	/**
	 * @return Returns the state.
	 */
	public String getState() {
		return state;
	}
	/**
	 * @param state The state to set.
	 */
	public void setState(String state) {
		this.state = state;
	}
	/**
	 * @return Returns the comments.
	 */
	public String getComments() {
		return comments;
	}
	/**
	 * @param comments The comments to set.
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}
	/**
	 * @return Returns the category.
	 */
	public java.lang.Integer getCategory() {
		return category;
	}
	/**
	 * @param category The category to set.
	 */
	public void setCategory(java.lang.Integer category) {
		this.category = category;
	}
	/**
	 * @return Returns the relations.
	 */
	public List getRelations() {
		return relations;
	}
	/**
	 * @param relations The relations to set.
	 */
	public void setRelations(List relations) {
		this.relations = relations;
	}
	/**
	 * @return Returns the bairro.
	 */
	public String getBairro() {
		return bairro;
	}
	/**
	 * @param bairro The bairro to set.
	 */
	public void setBairro(String bairro) {
		this.bairro = bairro;
	}
	/**
	 * @return Returns the lastUpdate.
	 */
	public Date getLastUpdate() {
		return lastUpdate;
	}
	/**
	 * @param lastUpdate The lastUpdate to set.
	 */
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
}

