
package org.eteamcs.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Entity Bean for the table contacts
 * @author Paulo Neves
 * Generated by Javalee v. 1.1
 * $Id$
 */
public class Contact extends BaseObject {
    private java.lang.Long contactId;
    private java.lang.String name;
    private java.lang.String title;
    private java.lang.String initials;
    private java.lang.String sex;
    private java.util.Date birthday;
    private java.lang.String streetAddress;
    private java.lang.String bairro;
    private java.lang.String postalCode;
    private java.lang.String city;
    private java.lang.String state;
    private java.lang.String country;
    private java.lang.String phone;
    private java.lang.String fax;
    private java.lang.String cellular;
    private java.lang.String email;
    private String email2;
    private java.lang.String url;
    private Companie company;
    private java.lang.String department;
    private java.lang.String function;
    private java.lang.String phoneWork;
    private java.lang.String faxWork;
    private java.lang.String cellularWork;
    private java.lang.String color;
    private java.lang.String comments;
    private List relations;
    private java.lang.Integer category;
    private List categories;
    private String indication;
    private Date lastUpdate;
    private java.lang.String username;
    private java.util.Date creationDate;

    /**
     * Constructor
     */
    public Contact() {
    	company = new Companie();
    	this.color="";
    	this.bairro="";
    	this.relations = new ArrayList();
    	this.categories = new ArrayList();
    }
	
    /**
     * Constructor
     */
    public Contact(java.lang.Long contactId, 
						java.lang.String name, 
						java.lang.String title, 
						java.lang.String initials, 
						java.lang.String sex, 
						java.util.Date birthday, 
						java.lang.String streetAddress, 
						java.lang.String postalCode, 
						java.lang.String city, 
						java.lang.String state, 
						java.lang.String country, 
						java.lang.String phone, 
						java.lang.String fax, 
						java.lang.String cellular, 
						java.lang.String email, 
						java.lang.String url, 
						Companie company, 
						java.lang.String department, 
						java.lang.String function, 
						java.lang.String phoneWork, 
						java.lang.String faxWork, 
						java.lang.String cellularWork, 
						java.lang.String color, 
						java.lang.String comments, 
						java.lang.String indication,
						java.lang.String username, 
						java.util.Date creationDate
						) {
		this.contactId=contactId;
		this.name=name;
		this.title=title;
		this.initials=initials;
		this.sex=sex;
		this.birthday=birthday;
		this.streetAddress=streetAddress;
		this.postalCode=postalCode;
		this.city=city;
		this.state=state;
		this.country=country;
		this.phone=phone;
		this.fax=fax;
		this.cellular=cellular;
		this.email=email;
		this.url=url;
		this.company=company;
		this.department=department;
		this.function=function;
		this.phoneWork=phoneWork;
		this.faxWork=faxWork;
		this.cellularWork=cellularWork;
		this.color=color;
		this.comments=comments;
		this.indication=indication;
		this.username=username;
		this.creationDate=creationDate;
		
		
	}	
    
    public java.lang.Long getId() {
      return this.contactId;
    }
    
    public void setContactId(java.lang.Long contactId) {
      this.contactId = contactId;
    }

    public java.lang.Long getContactId() {
      return this.contactId;
    }
    
    public void setName(java.lang.String name) {
      this.name = name;
    }

    public java.lang.String getName() {
      return this.name;
    }
    
    public void setTitle(java.lang.String title) {
      this.title = title;
    }

    public java.lang.String getTitle() {
      return this.title;
    }
    
    public void setInitials(java.lang.String initials) {
      this.initials = initials;
    }

    public java.lang.String getInitials() {
      return this.initials;
    }
    
    public void setSex(java.lang.String sex) {
      this.sex = sex;
    }

    public java.lang.String getSex() {
      return this.sex;
    }
    
    public void setBirthday(java.util.Date birthday) {
      this.birthday = birthday;
    }

    public java.util.Date getBirthday() {
      return this.birthday;
    }
    
    public void setStreetAddress(java.lang.String streetAddress) {
      this.streetAddress = streetAddress;
    }

    public java.lang.String getStreetAddress() {
      return this.streetAddress;
    }
    
    public void setPostalCode(java.lang.String postalCode) {
      this.postalCode = postalCode;
    }

    public java.lang.String getPostalCode() {
      return this.postalCode;
    }
    
    public void setCity(java.lang.String city) {
      this.city = city;
    }

    public java.lang.String getCity() {
      return this.city;
    }
    
    public void setState(java.lang.String state) {
      this.state = state;
    }

    public java.lang.String getState() {
      return this.state;
    }
    
    public void setCountry(java.lang.String country) {
      this.country = country;
    }

    public java.lang.String getCountry() {
      return this.country;
    }
    
    public void setPhone(java.lang.String phone) {
      this.phone = phone;
    }

    public java.lang.String getPhone() {
      return this.phone;
    }
    
    public void setFax(java.lang.String fax) {
      this.fax = fax;
    }

    public java.lang.String getFax() {
      return this.fax;
    }
    
    public void setCellular(java.lang.String cellular) {
      this.cellular = cellular;
    }

    public java.lang.String getCellular() {
      return this.cellular;
    }
    
    public void setEmail(java.lang.String email) {
      this.email = email;
    }

    public java.lang.String getEmail() {
      return this.email;
    }
    
    public void setUrl(java.lang.String url) {
      this.url = url;
    }

    public java.lang.String getUrl() {
      return this.url;
    }
    
    public void setCompany(Companie company) {
      this.company = company;
    }

    public Companie getCompany() {
      return this.company;
    }
    
    public void setDepartment(java.lang.String department) {
      this.department = department;
    }

    public java.lang.String getDepartment() {
      return this.department;
    }
    
    public void setFunction(java.lang.String function) {
      this.function = function;
    }

    public java.lang.String getFunction() {
      return this.function;
    }
    
    public void setPhoneWork(java.lang.String phoneWork) {
      this.phoneWork = phoneWork;
    }

    public java.lang.String getPhoneWork() {
      return this.phoneWork;
    }
    
    public void setFaxWork(java.lang.String faxWork) {
      this.faxWork = faxWork;
    }

    public java.lang.String getFaxWork() {
      return this.faxWork;
    }
    
    public void setCellularWork(java.lang.String cellularWork) {
      this.cellularWork = cellularWork;
    }

    public java.lang.String getCellularWork() {
      return this.cellularWork;
    }
    
    public void setColor(java.lang.String color) {
      this.color = color;
    }

    public java.lang.String getColor() {
      return this.color;
    }
    
    public void setComments(java.lang.String comments) {
      this.comments = comments;
    }

    public java.lang.String getComments() {
      return this.comments;
    }
    
    public void setUsername(java.lang.String username) {
      this.username = username;
    }

    public java.lang.String getUsername() {
      return this.username;
    }
    
    public void setCreationDate(java.util.Date creationDate) {
      this.creationDate = creationDate;
    }

    public java.util.Date getCreationDate() {
      return this.creationDate;
    }
    
	/**
	 * @return Returns the relations.
	 */
	public List getRelations() {
		return relations;
	}
	/**
	 * @param relations The relations to set.
	 */
	public void setRelations(List relations) {
		this.relations = relations;
	}
	/**
	 * @return Returns the category.
	 */
	public java.lang.Integer getCategory() {
		return category;
	}
	/**
	 * @param category The category to set.
	 */
	public void setCategory(java.lang.Integer category) {
		this.category = category;
	}
	
	/**
	 * @return Returns the categories.
	 */
	public List getCategories() {
		return categories;
	}
	/**
	 * @param relations The relations to set.
	 */
	public void setCategories(List categories) {
		this.categories = categories;
	}
	
	/**
	 * @return Returns the bairro.
	 */
	public java.lang.String getBairro() {
		return bairro;
	}
	/**
	 * @param bairro The bairro to set.
	 */
	public void setBairro(java.lang.String bairro) {
		this.bairro = bairro;
	}
	/**
	 * @return Returns the last_update.
	 */
	public Date getLastUpdate() {
		return lastUpdate;
	}
	/**
	 * @param last_update The last_update to set.
	 */
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
	/**
	 * @return Returns the email2.
	 */
	public String getEmail2() {
		return email2;
	}
	/**
	 * @param email2 The email2 to set.
	 */
	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getIndication() {
		return indication;
	}

	public void setIndication(String indication) {
		this.indication = indication;
	}
}

