package org.eteamcs.model;

import java.util.Date;

/**
 * Entity Bean for the table Relation
 * @author Paulo Neves
 * Generated by Javalee v. 1.1
 * $Id$
 */
public class Relation extends BaseObject {
    private java.lang.Long relationId;
    private java.lang.String name;
    private java.lang.Long parentId;
    private java.lang.String username;
    private String checked;
    private java.util.Date creationDate;

    /**
     * Constructor
     */
    public Relation() {
    }
	
    /**
     * Constructor
     */
    public Relation( Long relationId, String name, Long parentId, 
    		         String username, Date creationDate ) {
    	this.relationId = relationId;
    	this.name = name;
    	this.parentId = parentId;
    	this.username = username;
    	this.creationDate = creationDate;
	}	

    public Relation (Relation rel) {
		this(rel.getRelationId(), rel.getName(), rel.getParentId(), rel.getUsername(), rel.getCreationDate());
	}
    
    
	/**
	 * @return Returns the relationId.
	 */
	public java.lang.Long getRelationId() {
		return relationId;
	}
	/**
	 * @param categoryId The categoryId to set.
	 */
	public void setRelationId(java.lang.Long relationId) {
		this.relationId = relationId;
	}
	/**
	 * @return Returns the creationDate.
	 */
	public java.util.Date getCreationDate() {
		return creationDate;
	}
	/**
	 * @param creationDate The creationDate to set.
	 */
	public void setCreationDate(java.util.Date creationDate) {
		this.creationDate = creationDate;
	}
	/**
	 * @return Returns the name.
	 */
	public java.lang.String getName() {
		return name;
	}
	/**
	 * @param name The name to set.
	 */
	public void setName(java.lang.String name) {
		this.name = name;
	}
	/**
	 * @return Returns the parentId.
	 */
	public java.lang.Long getParentId() {
		return parentId;
	}
	/**
	 * @param parentId The parentId to set.
	 */
	public void setParentId(java.lang.Long parentId) {
		this.parentId = parentId;
	}
	/**
	 * @return Returns the username.
	 */
	public java.lang.String getUsername() {
		return username;
	}
	/**
	 * @param username The username to set.
	 */
	public void setUsername(java.lang.String username) {
		this.username = username;
	}
	/**
	 * @return Returns the checked.
	 */
	public String getChecked() {
		return checked;
	}
	/**
	 * @param checked The checked to set.
	 */
	public void setChecked(String checked) {
		this.checked = checked;
	}
	
}

