/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.eteamcs.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.MappingDispatchAction;
import org.apache.struts.upload.FormFile;
import org.eteamcs.io.ImportExcell;
import org.eteamcs.service.ICompanieManager;
import org.eteamcs.service.IContactManager;

/** 
 * MyEclipse Struts
 * Creation date: 01-03-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ImportContactsAction extends MappingDispatchAction {
	private final Log log = LogFactory.getLog(ImportContactsAction.class);
	private IContactManager contactManager = null;
    private ICompanieManager companyManager = null;
    private ImportExcell importExcell = null;
    
    
    public void setContactManager(IContactManager contactManager) {
        if( this.contactManager == null ) {
        	log.debug("set this.contactManager = contactManager");
        	this.contactManager = contactManager;
        }
    }	
    
    public void setCompanyManager(ICompanieManager companyManager) {
        if( this.companyManager == null ) {
        	log.debug("set this.companyManager = companyManager");
        	this.companyManager = companyManager;
        }
    } 
    
    public void setImportExcell(ImportExcell _importExcell) {
        if( this.importExcell == null ) {
        	log.debug("set this.importExcell = importExcell");
        	this.importExcell = _importExcell;
        }
    }
    
	/*
	 * Generated Methods
	 */

	public ActionForward uploadExcell(
			ActionMapping mapping,
			ActionForm form,
			HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		
		System.err.println("########### uploadExcell");
		System.out.println("########### uploadExcell");
		
		return mapping.findForward("success");
	}
	
	public ActionForward importFromExcell(
			ActionMapping mapping,
			ActionForm form,
			HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		
		DynaActionForm df = (DynaActionForm) form;
        if (log.isDebugEnabled()) {
            log.debug("entering importFromExcell method...");
        }
        
		System.err.println("########### ImportFromExcell");
		System.out.println("########### ImportFromExcell");
		// Process the FormFile
		//FileUpload formFile = (FileUpload) FormUtils.getFormValues(fileUploadForm,this,mapping,request);
		
		FormFile myFile = (FormFile) df.get("fileName");
        String contentType = myFile.getContentType();
        String fileName    = myFile.getFileName();
        int fileSize       = myFile.getFileSize();
        byte[] fileData    = myFile.getFileData();
        
	    System.out.println("contentType: " + contentType);
	    System.out.println("File Name: " + fileName);
	    System.out.println("File Size: " + fileSize);
    
	    
		importExcell.displayFromExcel(myFile.getInputStream());
    
		return mapping.findForward("import");
	}
}