package org.eteamcs.service.impl;

import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.eteamcs.dao.ICountryDAO;
import org.eteamcs.model.Country;
import org.eteamcs.service.ICountryManager;
import org.springframework.validation.Validator;


/**
 * Manager Implementation to table categorys
 * @author Paulo Neves
 * Generated by Javalee v. 1.1
 * $Id$
 */
public class CountryManager implements ICountryManager {
    private Log log = LogFactory.getLog(CountryManager.class);
    private ICountryDAO dao;
    private Validator validator;

    public void setCountryDAO(ICountryDAO dao) {
        this.dao = dao;
    }

    public void setValidator(Validator validator) {
    	this.validator = validator;
    }
    
    public List getCountries() {
        return dao.getCountries();
    }

    public Country getCountry(String acronym) {
        Country country = dao.getCountry(acronym);

        if (country == null) {
            log.warn("(acronym) '" + (acronym) + "' not found in database.");
        }

        return country;
    }

    public Country saveCountry(Country country) {
        /*BindException errors = new BindException(category, "category");
        validator.validate(category, errors);
        if (errors.hasErrors()) {
        	throw new RuntimeException("validation failed!", errors);
        }*/
        dao.saveCountry(country);

        return country;
    }

    public void removeCountry(String acronym) {
        dao.removeCountry(acronym);
    }
	
}
