package org.eteamcs.service.impl;

import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.eteamcs.dao.IRelationDAO;
import org.eteamcs.model.Relation;
import org.eteamcs.service.IRelationManager;
import org.springframework.validation.Validator;


/**
 * Manager Implementation to table relations
 * @author Paulo Neves
 * Generated by Javalee v. 1.1
 * $Id$
 */
public class RelationManager implements IRelationManager {
    private Log log = LogFactory.getLog(RelationManager.class);
    private IRelationDAO dao;
    private Validator validator;

    public void setRelationDAO(IRelationDAO dao) {
        this.dao = dao;
    }

    public void setValidator(Validator validator) {
    	this.validator = validator;
    }
    
    public List getRelations() {
        return dao.getRelations();
    }

    public Relation getRelation(Long relationId) {
        Relation relation = dao.getRelation(relationId);

        if (relation == null) {
            log.warn("(relationId) '" + (relationId) + "' not found in database.");
        }

        return relation;
    }

    public Relation saveRelation(Relation relation) {
        /*BindException errors = new BindException(relation, "relation");
        validator.validate(relation, errors);
        if (errors.hasErrors()) {
        	throw new RuntimeException("validation failed!", errors);
        }*/
        dao.saveRelation(relation);

        return relation;
    }

    public void removeRelation(java.lang.Long relationId) {
        dao.removeRelation(relationId);
    }
	
}
